services:
  postgres:
    image: postgres:17
    container_name: postgres
    restart: unless-stopped

    environment:
      POSTGRES_DB: matcha
      POSTGRES_USER: matcha
      POSTGRES_PASSWORD: matcha

    ports:
      - "5432:5432"

    volumes:
      - postgres_data:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4

    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin

    ports:
      - "5050:80"

    depends_on:
      - postgres

  back:
    build: ./back
    container_name: back
    env_file: ./back/.env

    environment:
      NODE_ENV: production
      DATABASE_URL: postgres://matcha:matcha@postgres:5432/matcha
      CORS_ORIGIN: http://localhost
      FRONTEND_URL: http://localhost
      COOKIE_SECURE: "false"

    depends_on:
      - postgres

    volumes:
      - uploads_data:/app/uploads

    restart: unless-stopped

  front:
    build: ./front
    container_name: front
    ports:
      - "8080:80"

    depends_on:
      - back

    volumes:
      - uploads_data:/usr/share/nginx/uploads:ro

    restart: unless-stopped

volumes:
  postgres_data:
  uploads_data: